### PR TITLE
Correcting exported module path

### PR DESCRIPTION
**Pull request by karoun**
This allows the library to be imported and matches the TypeScript config: https://github.com/quizlet/blurred/blob/858ab68900e1c6949f8d44dad80884ac98ae4197/tsconfig.json#L13

### CODE REVIEW

**Comment by idokutela** [comment]
Thanks

**Comment by karoun** [comment]
Thanks @idokutela! Could I trouble you to create a new version / release that includes this change?

**Comment by idokutela** [comment]
Presumably you mean a version bump in npm to reflect the change? It's been on my todo list, but I've been a bit busy (as we all are). I'll make sure it's done soonish -- beginning of the week probably. I've opened an issue -- if you don't see a bump by Tuesday, feel free to nag there.

Out of curiosity: what are you using blurred for? Any requests?

**Comment by karoun** [comment]
I'm using `blurred` together with Google's [Cloud Vision API](https://cloud.google.com/vision/) to detect text on images and blur it out for quizzing later. I chose it over some other similar packages because the core library makes no assumptions about where the image data is coming from. That makes it ideal for embedding in a Web Worker, something that's very important when blurring many regions at once!

**Comment by idokutela** [comment]
I've updated things, here and on npm. Note the version change - cosmetic changes to the API mean your imports may have to be renamed. In particular, if you were importing `blurred/lib/blur` for the types, now simply import `blurred`:

```js
// Previously: import blur from 'blur/lib/blur';
// Now:
import blur from 'blurred'; // already typed.
```

See the readme. Internally, though, nothing has changed, and function signatures remain the same.

I'm glad you've found blurred useful.

**Pull request merged**
